First, we import all the csv files for the results for ER tests.

In [1]:
import pandas as pd

# Specify file paths
file_names = [
    "er_posttest_lab.csv",
    "er_posttest_watrin.csv",
    "er_pretest_lab.csv",
    "er_pretest_watrin.csv"
]

# Load each file into a DataFrame and store them in a dictionary
dataframes = {name.rsplit('.', 1)[0]: pd.read_csv(name) for name in file_names}
print(dataframes)

{'er_posttest_lab':     roll_no  set     q1     q2     q3     q4     q5
0         1    0   True   True  False   True   True
1      1004    1  False  False  False   True  False
2      1015    0   True   True   True  False   True
3      1017    4  False  False   True  False  False
4      1036    2  False   True  False  False   True
5      1043    2  False  False  False   True  False
6      1047    1  False  False  False  False   True
7      1056    3  False   True   True  False  False
8         2    3  False   True  False  False  False
9       802    2  False  False  False  False  False
10      809    1   True  False  False  False  False
11      810    4  False  False   True  False  False
12      813    0   True   True  False   True   True
13      815    1   True  False  False   True  False
14      818    0   True   True  False  False   True
15      819    4  False  False   True  False   True
16      823    2  False   True  False  False   True
17      825    0   True   True  False   True   True
18      829    1   True  False  False   True   True
19      831    4  False   True   True  False   True
20      832    2  False  False  False  False   True
21      835    3   True   True  False  False  False
22      839    2  False  False  False  False   True
23      845    3   True   True  False  False  False
24      847    1   True  False  False  False  False
25      848    4  False  False  False  False  False
26      849    0   True   True   True  False   True
27      851    2  False  False  False  False  False
28      852    0   True   True  False   True   True
29      854    2  False  False  False   True  False
30      906    1   True  False  False  False  False
31      911    2  False  False  False  False   True
32      914    4  False  False  False  False  False
33      916    3   True   True  False  False  False
34      921    1   True  False  False   True  False
35      924    3   True  False  False   True  False
36      935    2  False  False  False  False   True
37      936    3   True  False  False  False  False
38      937    3   True   True   True  False  False
39      938    0   True   True   True   True   True
40      940    1   True  False  False  False  False
41      941    2  False   True   True  False   True
42      942    0   True   True   True   True   True
43      944    1   True  False  False  False   True
44      947    2  False  False   True  False   True
45      948    0  False  False   True   True  False
46      951    4  False  False  False   True   True
47      955    0   True   True  False  False  False
48      957    2  False  False  False  False  False, 'er_posttest_watrin':     roll_no  set     q1     q2     q3     q4     q5
0      1001    1   True  False   True   True  False
1      1003    1  False  False   True  False  False
2      1006    2  False  False  False  False  False
3      1007    1  False   True  False  False   True
4      1008    2  False  False  False  False   True
5      1009    0   True   True  False  False   True
6      1011    1   True  False  False   True  False
7      1012    3   True   True  False  False  False
8      1018    4  False  False   True  False   True
9      1021    0   True   True  False   True   True
10     1026    3   True   True  False   True  False
11     1029    2  False  False  False  False   True
12     1030    0   True   True  False  False   True
13     1031    3   True   True  False  False  False
14     1032    2  False  False  False  False  False
15     1033    4  False  False  False  False   True
16     1034    4  False  False   True  False   True
17     1037    1   True  False  False   True   True
18     1039    1   True  False  False  False  False
19     1040    4  False   True   True  False   True
20     1041    0   True   True  False   True   True
21     1042    1   True  False  False   True  False
22     1048    4  False  False  False  False  False
23     1049    0   True   True   True   True   True
24     1051    2  False  False  False  False  False
25     1052    3   True   True  False  False  False
26     1053    4   True  False   True  False   True
27     1057    1   True  False  False  False  False
28      805    3   True  False  False   True  False
29      806    4  False  False   True  False  False
30      807    2  False  False  False  False   True
31      814    4  False  False   True  False   True
32      821    0   True   True   True  False  False
33      826    1   True  False  False  False  False
34      827    4  False  False  False  False   True
35      840    3   True   True  False  False  False
36      843    2  False  False  False   True  False
37      903    0   True   True  False  False  False
38      904    1   True  False  False  False  False
39      905    3   True   True  False  False  False
40      909    3  False   True  False  False  False
41      910    2  False  False  False  False   True
42      912    2  False  False  False  False   True
43      919    4  False  False   True  False  False
44      923    4   True  False  False   True   True
45      926    0   True   True   True  False   True
46      927    2  False   True  False  False   True
47      929    3   True   True  False  False  False
48      930    2  False  False  False  False   True
49      932    0   True   True   True  False   True
50      934    2  False   True  False  False   True
51      943    1   True  False  False  False  False
52      945    3   True   True  False  False  False
53      950    4   True  False  False  False  False
54      952    0   True   True  False  False   True
55      953    0   True   True  False   True   True
56      954    4  False  False   True  False  False
57      956    0  False   True  False  False  False, 'er_pretest_lab':     roll_no  set     q1     q2     q3     q4     q5
0         1    3  False  False  False  False  False
1      1004    1  False   True   True   True  False
2      1015    2   True  False  False  False   True
3      1017    3  False  False  False  False   True
4      1036    4  False   True   True  False   True
5      1043    1  False  False  False   True  False
6      1047    0   True  False  False  False  False
7      1056    3  False  False  False  False   True
8         2    0  False  False   True  False  False
9       802    3   True  False  False   True   True
10      809    1  False   True  False  False  False
11      810    4  False   True  False   True   True
12      813    0   True   True  False  False  False
13      815    2   True  False  False  False  False
14      818    0   True  False   True  False  False
15      819    3  False   True  False  False  False
16      823    1  False   True   True  False  False
17      825    0  False  False  False   True  False
18      829    0  False   True  False  False  False
19      831    4  False   True   True  False   True
20      832    4  False   True  False   True  False
21      833    0  False  False  False  False   True
22      835    3  False   True  False  False  False
23      839    2  False  False  False  False  False
24      845    1   True  False   True   True   True
25      847    0   True  False   True  False   True
26      848    0  False  False   True   True  False
27      849    2  False  False  False  False  False
28      851    3   True   True  False  False  False
29      852    0  False  False   True   True  False
30      854    1  False  False   True  False  False
31      906    3  False  False  False   True   True
32      911    0   True   True   True   True  False
33      914    2  False  False  False  False  False
34      916    3   True   True   True  False  False
35      921    3  False   True  False  False   True
36      924    2  False  False   True  False  False
37      935    4  False   True  False   True  False
38      936    4  False  False  False  False   True
39      937    3   True   True  False  False  False
40      938    0  False   True   True   True  False
41      940    1  False   True   True   True  False
42      941    2   True   True  False   True   True
43      942    1  False  False  False  False  False
44      944    4  False  False  False  False  False
45      947    2   True  False  False   True  False
46      948    1  False  False  False   True  False
47      951    1  False  False  False  False  False
48      955    3   True   True  False  False  False, 'er_pretest_watrin':     roll_no  set     q1     q2     q3     q4     q5
0      1001    0   True  False   True   True  False
1      1003    2   True   True  False  False  False
2      1006    2  False  False  False  False  False
3      1007    2  False  False   True  False  False
4      1008    0   True   True   True   True  False
5      1009    2  False   True  False   True  False
6      1011    3   True   True  False  False  False
7      1012    3   True   True  False  False  False
8      1018    0   True  False   True  False  False
9      1021    3   True   True  False   True  False
10     1026    1  False  False  False  False  False
11     1029    4   True   True  False  False  False
12     1030    2  False  False   True  False  False
13     1031    4  False  False  False  False  False
14     1032    4  False  False  False   True   True
15     1033    1  False   True   True  False   True
16     1034    3  False   True  False  False  False
17     1037    2  False  False  False  False  False
18     1039    3   True   True  False  False   True
19     1040    3   True   True  False  False  False
20     1041    0  False  False  False  False  False
21     1042    0  False   True   True  False   True
22     1048    2   True  False  False  False  False
23     1049    3   True   True  False  False  False
24     1051    3  False  False  False   True  False
25     1052    0   True   True  False  False  False
26     1053    4  False   True  False  False   True
27     1057    4  False  False  False  False   True
28      805    0  False   True   True   True  False
29      806    2   True  False  False  False  False
30      807    1  False  False  False  False  False
31      814    1  False   True   True  False  False
32      821    0  False  False   True   True  False
33      826    3   True   True  False  False   True
34      827    4  False  False   True   True   True
35      840    4  False   True  False   True   True
36      843    0   True  False  False  False  False
37      903    0  False  False  False   True  False
38      904    3   True   True  False  False  False
39      909    0  False  False   True   True  False
40      910    4  False   True  False  False   True
41      912    2  False   True  False  False  False
42      919    4  False   True   True  False   True
43      923    3  False   True  False  False  False
44      926    2   True  False  False   True  False
45      927    4  False   True   True  False   True
46      929    0   True  False   True   True  False
47      930    2   True   True  False  False   True
48      932    1  False  False  False  False  False
49      934    4   True   True  False   True  False
50      943    2   True  False  False  False  False
51      945    1   True   True  False  False  False
52      950    1  False  False  False   True  False
53      952    4  False   True   True  False   True
54      953    0   True  False  False   True  False
55      954    1  False   True   True   True  False
56      956    0  False   True  False  False  False}

Now, we calculate scores for each student in their pretest and posttest.

In [2]:
for name, df in dataframes.items():
    print(name)
    df['score'] = df.iloc[:, 2:].apply(lambda col: sum(col == True), axis=1)
    print(df[["roll_no","score"]])

er_posttest_lab
    roll_no  score
0         1      4
1      1004      1
2      1015      4
3      1017      1
4      1036      2
5      1043      1
6      1047      1
7      1056      2
8         2      1
9       802      0
10      809      1
11      810      1
12      813      4
13      815      2
14      818      3
15      819      2
16      823      2
17      825      4
18      829      3
19      831      3
20      832      1
21      835      2
22      839      1
23      845      2
24      847      1
25      848      0
26      849      4
27      851      0
28      852      4
29      854      1
30      906      1
31      911      1
32      914      0
33      916      2
34      921      2
35      924      2
36      935      1
37      936      1
38      937      3
39      938      5
40      940      1
41      941      3
42      942      5
43      944      2
44      947      2
45      948      2
46      951      2
47      955      2
48      957      0
er_posttest_watrin
    roll_no  score
0      1001      3
1      1003      1
2      1006      0
3      1007      2
4      1008      1
5      1009      3
6      1011      2
7      1012      2
8      1018      2
9      1021      4
10     1026      3
11     1029      1
12     1030      3
13     1031      2
14     1032      0
15     1033      1
16     1034      2
17     1037      3
18     1039      1
19     1040      3
20     1041      4
21     1042      2
22     1048      0
23     1049      5
24     1051      0
25     1052      2
26     1053      3
27     1057      1
28      805      2
29      806      1
30      807      1
31      814      2
32      821      3
33      826      1
34      827      1
35      840      2
36      843      1
37      903      2
38      904      1
39      905      2
40      909      1
41      910      1
42      912      1
43      919      1
44      923      3
45      926      4
46      927      2
47      929      2
48      930      1
49      932      4
50      934      2
51      943      1
52      945      2
53      950      1
54      952      3
55      953      4
56      954      1
57      956      1
er_pretest_lab
    roll_no  score
0         1      0
1      1004      3
2      1015      2
3      1017      1
4      1036      3
5      1043      1
6      1047      1
7      1056      1
8         2      1
9       802      3
10      809      1
11      810      3
12      813      2
13      815      1
14      818      2
15      819      1
16      823      2
17      825      1
18      829      1
19      831      3
20      832      2
21      833      1
22      835      1
23      839      0
24      845      4
25      847      3
26      848      2
27      849      0
28      851      2
29      852      2
30      854      1
31      906      2
32      911      4
33      914      0
34      916      3
35      921      2
36      924      1
37      935      2
38      936      1
39      937      2
40      938      3
41      940      3
42      941      4
43      942      0
44      944      0
45      947      2
46      948      1
47      951      0
48      955      2
er_pretest_watrin
    roll_no  score
0      1001      3
1      1003      2
2      1006      0
3      1007      1
4      1008      4
5      1009      2
6      1011      2
7      1012      2
8      1018      2
9      1021      3
10     1026      0
11     1029      2
12     1030      1
13     1031      0
14     1032      2
15     1033      3
16     1034      1
17     1037      0
18     1039      3
19     1040      2
20     1041      0
21     1042      3
22     1048      1
23     1049      2
24     1051      1
25     1052      2
26     1053      2
27     1057      1
28      805      3
29      806      1
30      807      0
31      814      2
32      821      2
33      826      3
34      827      3
35      840      3
36      843      1
37      903      1
38      904      2
39      909      2
40      910      2
41      912      1
42      919      3
43      923      1
44      926      2
45      927      3
46      929      3
47      930      3
48      932      0
49      934      3
50      943      1
51      945      2
52      950      1
53      952      3
54      953      2
55      954      3
56      956      1

Now for each student, we check if their performance was better in their posttest.

In [4]:
lab_group_df=pd.merge(dataframes["er_pretest_lab"],dataframes["er_posttest_lab"],on="roll_no",how="inner",suffixes=["_pre","_post"])

# print(lab_group_df[["roll_no","score_pre", "score_post"]])
increase_set=lab_group_df[lab_group_df["score_pre"]<lab_group_df["score_post"]]
decreased_set=lab_group_df[lab_group_df["score_pre"]>lab_group_df["score_post"]]
neutral_set=lab_group_df[lab_group_df["score_pre"]==lab_group_df["score_post"]]


print(increase_set[["roll_no","score_pre", "score_post"]])
print(decreased_set[["roll_no","score_pre", "score_post"]])
print(neutral_set[["roll_no","score_pre", "score_post"]])

    roll_no  score_pre  score_post
0         1          0           4
2      1015          2           4
7      1056          1           2
12      813          2           4
13      815          1           2
14      818          2           3
15      819          1           2
17      825          1           4
18      829          1           3
21      835          1           2
22      839          0           1
26      849          0           4
28      852          2           4
35      924          1           2
38      937          2           3
39      938          3           5
42      942          0           5
43      944          0           2
45      948          1           2
46      951          0           2
    roll_no  score_pre  score_post
1      1004          3           1
4      1036          3           2
9       802          3           0
11      810          3           1
20      832          2           1
23      845          4           2
24      847          3           1
25      848          2           0
27      851          2           0
30      906          2           1
31      911          4           1
33      916          3           2
36      935          2           1
40      940          3           1
41      941          4           3
    roll_no  score_pre  score_post
3      1017          1           1
5      1043          1           1
6      1047          1           1
8         2          1           1
10      809          1           1
16      823          2           2
19      831          3           3
29      854          1           1
32      914          0           0
34      921          2           2
37      936          1           1
44      947          2           2
47      955          2           2